### ISSUE TITLE
config.yml

### ISSUE THREAD

**Issue by kuro46** [kuro46/ScriptBlock-Improved#38]
```yml
cancelInteract: bool
cancelMove: bool
cancelPress: bool
cancelSBInteract: bool
cancelSBWalk: bool
```
