### ISSUE TITLE
Default options

### ISSUE THREAD

**Issue by kuro46** [kuro46/ScriptBlock-Improved#50]
Like this:
```yml
default-opts:
  *: "@say A"
  move: "@say B"
  sbwalk: "@say B"
```
